//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ARMS_Details
    {
        public int Rates_ID { get; set; }
        public Nullable<int> ARMS_Risks_Sub_ID { get; set; }
        public Nullable<double> Misc_High { get; set; }
        public Nullable<double> Misc_Low { get; set; }
        public Nullable<double> Contract_High { get; set; }
        public Nullable<double> Contract_Low { get; set; }
    }
}
