//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_WIPData
    {
        public int WIPId { get; set; }
        public Nullable<decimal> Original_Contract { get; set; }
        public Nullable<decimal> Original_Profit { get; set; }
        public string Owner_Job_Description { get; set; }
        public string Job_Number { get; set; }
        public Nullable<decimal> Contract_Price_Change_Orders { get; set; }
        public Nullable<decimal> Total_Billed_ToDate_Incl_Retainage { get; set; }
        public Nullable<decimal> Total_Cost_To_Date { get; set; }
        public Nullable<decimal> Total_Revised_Est_cost_to_complete { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<decimal> RevisedEstcostofchangeorders { get; set; }
        public Nullable<decimal> revisedestgrossprofit { get; set; }
        public Nullable<decimal> grossprofitmargin { get; set; }
        public Nullable<decimal> costpccomplete { get; set; }
        public Nullable<decimal> grossprofitearnedtodate { get; set; }
        public Nullable<decimal> grossprofittobeearned { get; set; }
        public Nullable<decimal> costestearninexcessofbill { get; set; }
        public Nullable<decimal> billinsinearnofcostestearn { get; set; }
        public Nullable<decimal> purejobborrow { get; set; }
        public Nullable<decimal> cashflowremaining { get; set; }
        public Nullable<System.DateTime> AsofDate { get; set; }
        public string BondNumber { get; set; }
        public Nullable<byte> Job_Status { get; set; }
    }
}
