//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAms_BondTaxFee
    {
        public int BondDetailTaxFeeID { get; set; }
        public Nullable<int> TaxFeeID { get; set; }
        public Nullable<int> BondID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ForeignAmount { get; set; }
    
        public virtual ArgAMS_BondDetail ArgAMS_BondDetail { get; set; }
        public virtual ArgAMS_TaxFee ArgAMS_TaxFee { get; set; }
    }
}
