//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_SnP_Equivalent_Rating_Mst
    {
        public int SnP_Rating_ID { get; set; }
        public Nullable<double> Int_Coverage { get; set; }
        public Nullable<double> FCF_TD { get; set; }
        public Nullable<double> OI_Sales { get; set; }
        public Nullable<double> Total_Debt_Total_Cap { get; set; }
        public Nullable<double> Return_on_Capital { get; set; }
        public Nullable<double> Total_Capital { get; set; }
        public Nullable<double> Ranking { get; set; }
    }
}
