//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_RateCalculator
    {
        public int RateCalculatorID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<decimal> TotalDebt { get; set; }
        public Nullable<decimal> NetSales { get; set; }
        public Nullable<decimal> EBIT { get; set; }
        public Nullable<decimal> InterestExpense { get; set; }
        public Nullable<decimal> OperatingIncome { get; set; }
        public Nullable<decimal> CashFlowFromOperations { get; set; }
        public Nullable<decimal> CapitalExpenditures { get; set; }
        public Nullable<decimal> SNPEquivalentRatingID { get; set; }
        public Nullable<decimal> UWAdjustmentID { get; set; }
    }
}
