//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_RateSnPEquivalent
    {
        public int SnPRatingID { get; set; }
        public Nullable<double> InterestCoverage { get; set; }
        public Nullable<double> FreeCashFlowToTotalDebt { get; set; }
        public Nullable<double> OperatingIncomeToNetSales { get; set; }
        public Nullable<double> TotalDebtToTotalCapital { get; set; }
        public Nullable<double> ReturnOnCapital { get; set; }
        public Nullable<double> TotalCapital { get; set; }
        public Nullable<double> Ranking { get; set; }
    }
}
