//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_FinancialHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_FinancialHeader()
        {
            this.ArgAMS_FinancialBalanceSheet = new HashSet<ArgAMS_FinancialBalanceSheet>();
            this.ArgAMS_FinancialCashFlow = new HashSet<ArgAMS_FinancialCashFlow>();
            this.ArgAMS_FinancialIncomeStatementLineItem = new HashSet<ArgAMS_FinancialIncomeStatementLineItem>();
        }
    
        public long StatementID { get; set; }
        public int StatementTypeID { get; set; }
        public int PeriodID { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> CPACompletionDate { get; set; }
        public System.DateTime StatementDate { get; set; }
        public string CurrencyDenomination { get; set; }
        public long AccountNumber { get; set; }
        public System.DateTime PeriodEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> InterimMonths { get; set; }
        public Nullable<int> CPAReputation { get; set; }
        public Nullable<int> QualityOfPresentation { get; set; }
        public Nullable<int> QualityOfIAS { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string EntityName { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_FinancialBalanceSheet> ArgAMS_FinancialBalanceSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_FinancialCashFlow> ArgAMS_FinancialCashFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_FinancialIncomeStatementLineItem> ArgAMS_FinancialIncomeStatementLineItem { get; set; }
        public virtual ArgAMS_FinancialHeader ArgAMS_FinancialHeader1 { get; set; }
        public virtual ArgAMS_FinancialHeader ArgAMS_FinancialHeader2 { get; set; }
    }
}
