//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_Account_fix
    {
        public long AccountNumber { get; set; }
        public int BusinessTypeID { get; set; }
        public int StatusID { get; set; }
        public int LocationID { get; set; }
        public int UW1ID { get; set; }
        public Nullable<int> UW2ID { get; set; }
        public int UWAId { get; set; }
        public Nullable<int> HomeOffice2Id { get; set; }
        public Nullable<int> HomeOffice1ID { get; set; }
        public int AgencyID { get; set; }
        public int PrincipalID { get; set; }
        public Nullable<int> PriorSuretyID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> NoteId { get; set; }
        public Nullable<System.DateTime> Mgmtcontroldt { get; set; }
        public Nullable<System.DateTime> Argoacqdt { get; set; }
        public Nullable<System.DateTime> LastAcctMtg { get; set; }
        public Nullable<bool> isQuoted { get; set; }
        public Nullable<bool> isProspect { get; set; }
        public Nullable<bool> isManualAddress { get; set; }
    }
}
