//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractConstOps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_ContractConstOps()
        {
            this.ArgAMS_ContractConstOpsExperience = new HashSet<ArgAMS_ContractConstOpsExperience>();
        }
    
        public int ConstOpsID { get; set; }
        public int PrimaryTradeID { get; set; }
        public Nullable<int> SecondaryTradeID { get; set; }
        public string TradeRegion { get; set; }
        public Nullable<int> Publicpercent { get; set; }
        public Nullable<int> privatepercent { get; set; }
        public Nullable<int> Primepercent { get; set; }
        public Nullable<int> Subpercent { get; set; }
        public int AccountNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_ContractConstOpsExperience> ArgAMS_ContractConstOpsExperience { get; set; }
    }
}
