//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondContractRatePlan
    {
        public int BondRateID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> BondID { get; set; }
        public Nullable<decimal> BondAmount { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public Nullable<double> CommissionPercent { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Premium { get; set; }
    
        public virtual ArgAMS_BondDetail ArgAMS_BondDetail { get; set; }
    }
}
