//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_Principal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_Principal()
        {
            this.ArgAMS_Account = new HashSet<ArgAMS_Account>();
            this.ArgAMS_BondPrincipal = new HashSet<ArgAMS_BondPrincipal>();
        }
    
        public int PrincipalID { get; set; }
        public string PrincipalName { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<int> SICCode { get; set; }
        public Nullable<int> PrinipalTypeID { get; set; }
        public Nullable<bool> ForeignOwned { get; set; }
        public Nullable<bool> PublicTraded { get; set; }
        public string Ticker { get; set; }
        public Nullable<int> ExchangeID { get; set; }
        public Nullable<bool> Confidentiality { get; set; }
        public Nullable<System.DateTime> ConfidentialityDate { get; set; }
        public Nullable<bool> Babkruptcy { get; set; }
        public Nullable<System.DateTime> BankruptcyDate { get; set; }
        public Nullable<bool> WatchList { get; set; }
        public Nullable<System.DateTime> WatchListDate { get; set; }
        public Nullable<bool> Collateral { get; set; }
        public Nullable<System.DateTime> CollateralDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public Nullable<long> RefAccountNumber { get; set; }
        public Nullable<long> AccountID { get; set; }
        public Nullable<bool> PrivateEquityOwned { get; set; }
        public string OpenClaim { get; set; }
        public Nullable<int> PrivateEquityOwnedListId { get; set; }
        public Nullable<System.DateTime> PEInceptionDate { get; set; }
        public Nullable<int> CapIQId { get; set; }
        public Nullable<System.DateTime> CapIQUploadDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_Account> ArgAMS_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondPrincipal> ArgAMS_BondPrincipal { get; set; }
    }
}
