//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_TaxFeeState
    {
        public int TaxFeeStateID { get; set; }
        public int TaxFeeID { get; set; }
        public string StateAbbr { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual ArgAMS_TaxFee ArgAMS_TaxFee { get; set; }
    }
}
