//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ProducerCSR
    {
        public int AgentId { get; set; }
        public long AccountNumber { get; set; }
        public string AgentName { get; set; }
        public int AgentTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string EmailId { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
    }
}
