//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractCreditBankLine
    {
        public int BankLineID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<System.DateTime> BankLetterDate { get; set; }
        public string BankName { get; set; }
        public Nullable<int> GurantorID { get; set; }
        public Nullable<int> Security1ID { get; set; }
        public Nullable<int> Security2ID { get; set; }
        public Nullable<int> Security3ID { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<bool> CopyCurrentNote { get; set; }
        public Nullable<bool> CopySecurityAgmt { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<int> CreditID { get; set; }
    
        public virtual ArgAMS_ContractCredit ArgAMS_ContractCredit { get; set; }
    }
}
