//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAms_ContractRateStep
    {
        public int ContractRateStepID { get; set; }
        public decimal LowerLimit { get; set; }
        public decimal UpperLimit { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<int> ContractRatePlanID { get; set; }
    
        public virtual ArgAMS_ContractRatePlan ArgAMS_ContractRatePlan { get; set; }
    }
}
