//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_SelfAuditAnswers
    {
        public int AnswerID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> SelfAuditID { get; set; }
    }
}
