//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondFrontingBroker
    {
        public int BondFrontingCompanyID { get; set; }
        public Nullable<int> WritingCompanyID { get; set; }
        public Nullable<int> AgentID { get; set; }
    
        public virtual ArgAgency_AgentDetail ArgAgency_AgentDetail { get; set; }
    }
}
