//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_AccountCommercialCredit
    {
        public long AcctRatingID { get; set; }
        public string RatingType { get; set; }
        public int RatingID { get; set; }
        public int RatingCategoryID { get; set; }
        public Nullable<System.DateTime> AsofDate { get; set; }
        public Nullable<int> RatingOutlookID { get; set; }
        public Nullable<bool> RatingWatchList { get; set; }
        public Nullable<int> RatingDirectionID { get; set; }
        public long AccountNumber { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        public virtual ArgAMS_AccountCommercialCredit ArgAMS_AccountCommercialCredit1 { get; set; }
        public virtual ArgAMS_AccountCommercialCredit ArgAMS_AccountCommercialCredit2 { get; set; }
        public virtual ArgAMS_CommercialCreditDirection ArgAMS_CommercialCreditDirection { get; set; }
        public virtual ArgAMS_CommercialCreditOutlook ArgAMS_CommercialCreditOutlook { get; set; }
        public virtual ArgAMS_CommercialSystemRatingCategory ArgAMS_CommercialSystemRatingCategory { get; set; }
    }
}
