//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractRateClassCode
    {
        public int ContractRateClassCodeID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> BondClassCodeID { get; set; }
    
        public virtual ArgAMS_BondClassCode ArgAMS_BondClassCode { get; set; }
        public virtual ArgAMS_ContractRateDetails ArgAMS_ContractRateDetails { get; set; }
    }
}
