//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_RateDetail
    {
        public int RateID { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<byte> RatingCategoryID { get; set; }
        public Nullable<byte> MiscRateStructureID { get; set; }
        public Nullable<byte> ContractRateStructureID { get; set; }
        public Nullable<bool> IsMiscHigh { get; set; }
        public Nullable<bool> IsMiscLow { get; set; }
        public Nullable<bool> IsContractHigh { get; set; }
        public Nullable<bool> IsContractLow { get; set; }
        public Nullable<byte> RateStatusID { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<byte> CompanyTypeID { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public Nullable<int> SNPRatingID { get; set; }
        public Nullable<int> CreditRanking { get; set; }
        public Nullable<decimal> CreditRatingFactor { get; set; }
        public Nullable<decimal> NetWorth { get; set; }
        public Nullable<decimal> MiscLiability { get; set; }
        public Nullable<decimal> CapacityToCapitalMiscFactor { get; set; }
        public Nullable<decimal> ContractLiability { get; set; }
        public Nullable<decimal> CapacityToCapitalContractFactor { get; set; }
        public Nullable<byte> CollateralID { get; set; }
        public Nullable<decimal> CollateralFactor { get; set; }
        public Nullable<decimal> MiscHighExposure { get; set; }
        public Nullable<decimal> MiscHighExposureFactor { get; set; }
        public Nullable<decimal> MiscLowExposure { get; set; }
        public Nullable<byte> MiscLowExposureTypeID { get; set; }
        public Nullable<decimal> MiscLowExposureFactor { get; set; }
        public Nullable<decimal> ContractHighExposure { get; set; }
        public Nullable<byte> ContractHighExposureTypeID { get; set; }
        public Nullable<decimal> ContractHighExposureFactor { get; set; }
        public Nullable<decimal> ContractLowExposure { get; set; }
        public Nullable<byte> ContractLowExposureTypeID { get; set; }
        public Nullable<decimal> ContractLowExposureFactor { get; set; }
        public Nullable<byte> MiscHighTermTypeID { get; set; }
        public Nullable<decimal> MiscHighTermTypeFactor { get; set; }
        public Nullable<byte> MiscLowTermTypeID { get; set; }
        public Nullable<decimal> MiscLowTermTypeFactor { get; set; }
        public Nullable<byte> ContractHighTermTypeID { get; set; }
        public Nullable<decimal> ContractHighTermTypeFactor { get; set; }
        public Nullable<byte> ContractLowTermTypeID { get; set; }
        public Nullable<decimal> ContractLowTermTypeFactor { get; set; }
        public Nullable<byte> MiscHighFormTypeID { get; set; }
        public Nullable<decimal> MiscHighFormTypeFactor { get; set; }
        public Nullable<byte> MiscLowFormTypeID { get; set; }
        public Nullable<decimal> MiscLowFormTypeFactor { get; set; }
        public Nullable<byte> ContractHighFormTypeID { get; set; }
        public Nullable<decimal> ContractHighFormTypeFactor { get; set; }
        public Nullable<byte> ContractLowFormTypeID { get; set; }
        public Nullable<decimal> ContractLowFormTypeFactor { get; set; }
        public Nullable<byte> MiscHighExpenseTypeID { get; set; }
        public Nullable<decimal> MiscHighExpenseTypeFactor { get; set; }
        public Nullable<byte> MiscLowExpenseTypeID { get; set; }
        public Nullable<decimal> MiscLowExpenseTypeFactor { get; set; }
        public Nullable<byte> ContractHighExpenseTypeID { get; set; }
        public Nullable<decimal> ContractHighExpenseTypeFactor { get; set; }
        public Nullable<byte> ContractLowExpenseTypeID { get; set; }
        public Nullable<decimal> ContractLowExpenseTypeFactor { get; set; }
        public Nullable<decimal> MiscHighARM { get; set; }
        public Nullable<decimal> MiscLowARM { get; set; }
        public Nullable<decimal> ContractHighARM { get; set; }
        public Nullable<decimal> ContractLowARM { get; set; }
        public Nullable<decimal> MiscCompositeCommission { get; set; }
        public Nullable<decimal> MiscHighCommission { get; set; }
        public Nullable<decimal> MiscLowCommission { get; set; }
        public Nullable<decimal> ContractCompositeCommission { get; set; }
        public Nullable<decimal> ContractHighCommission { get; set; }
        public Nullable<decimal> ContractLowCommission { get; set; }
        public Nullable<decimal> MiscCompositeNet { get; set; }
        public Nullable<decimal> MiscCompositeGross { get; set; }
        public Nullable<decimal> MiscHighNet { get; set; }
        public Nullable<decimal> MiscHighGross { get; set; }
        public Nullable<decimal> MiscLowNet { get; set; }
        public Nullable<decimal> MiscLowGross { get; set; }
        public Nullable<decimal> ContractCompositeNet { get; set; }
        public Nullable<decimal> ContractCompositeGross { get; set; }
        public Nullable<decimal> ContractHighNet { get; set; }
        public Nullable<decimal> ContractHighGross { get; set; }
        public Nullable<decimal> ContractLowNet { get; set; }
        public Nullable<decimal> ContractLowGross { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IndividualPurge { get; set; }
    }
}
