//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractRatePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_ContractRatePlan()
        {
            this.ArgAms_ContractRateStep = new HashSet<ArgAms_ContractRateStep>();
        }
    
        public int ContractRatePlanID { get; set; }
        public Nullable<int> ContractRateTypeID { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> SystemEffectiveDate { get; set; }
        public Nullable<System.DateTime> SystemEntryDate { get; set; }
        public string PlanName { get; set; }
    
        public virtual ArgAMS_ContractRateType ArgAMS_ContractRateType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAms_ContractRateStep> ArgAms_ContractRateStep { get; set; }
    }
}
