//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_AccountWatchListActionPlan
    {
        public int ActionPlanID { get; set; }
        public Nullable<int> WatchListID { get; set; }
        public string ActionPlan { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ActionResult { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string Outlook { get; set; }
    
        public virtual ArgAMS_AccountWatchList ArgAMS_AccountWatchList { get; set; }
        public virtual ArgAMS_AccountWatchList ArgAMS_AccountWatchList1 { get; set; }
    }
}
