//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondTransactionForeign
    {
        public int BondTransactionForeignId { get; set; }
        public Nullable<int> BondTransactionId { get; set; }
        public Nullable<int> BondTransTypeId { get; set; }
        public Nullable<int> BondId { get; set; }
        public Nullable<int> EndorsementId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<bool> RateOverride { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<System.DateTime> ExchangeRateDate { get; set; }
        public Nullable<decimal> ForeignBondAmount { get; set; }
        public Nullable<decimal> TotalForeignPremium { get; set; }
        public Nullable<decimal> ForeignPremium { get; set; }
        public Nullable<decimal> TotalForeignCommission { get; set; }
        public Nullable<decimal> ForeignCommission { get; set; }
        public Nullable<decimal> ForeignTotalTaxFee { get; set; }
        public Nullable<decimal> InsurancePremiumTax { get; set; }
    }
}
