//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAgency_AgentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAgency_AgentDetail()
        {
            this.ArgAMS_BondFrontingBroker = new HashSet<ArgAMS_BondFrontingBroker>();
        }
    
        public int AgentID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int TitleTypeID { get; set; }
        public int AgentTypeID { get; set; }
        public int AgencyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ArgAMS_Agency ArgAMS_Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondFrontingBroker> ArgAMS_BondFrontingBroker { get; set; }
    }
}
