//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractIndemnity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_ContractIndemnity()
        {
            this.ArgAMS_ContractIndemnitors = new HashSet<ArgAMS_ContractIndemnitors>();
            this.ArgAMS_ContractIndemnityAddlIndemnitor = new HashSet<ArgAMS_ContractIndemnityAddlIndemnitor>();
            this.ArgAMS_ContractIndemnityILOC = new HashSet<ArgAMS_ContractIndemnityILOC>();
            this.ArgAMS_ContractIndemnitySubOrdination = new HashSet<ArgAMS_ContractIndemnitySubOrdination>();
        }
    
        public int IndemnityID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int NoteID { get; set; }
        public long AccountNumber { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_ContractIndemnitors> ArgAMS_ContractIndemnitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_ContractIndemnityAddlIndemnitor> ArgAMS_ContractIndemnityAddlIndemnitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_ContractIndemnityILOC> ArgAMS_ContractIndemnityILOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_ContractIndemnitySubOrdination> ArgAMS_ContractIndemnitySubOrdination { get; set; }
    }
}
