//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_InvoiceErrorDetail
    {
        public int Id { get; set; }
        public Nullable<int> BondId { get; set; }
        public Nullable<int> BondTransactionId { get; set; }
        public string ErrorDetail { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
    }
}
