//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_Rates_Details
    {
        public int Rates_ID { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string State_Name { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<int> Company_Type_ID { get; set; }
        public Nullable<int> SnP_Rating_ID { get; set; }
        public Nullable<decimal> Net_WORTH { get; set; }
        public Nullable<decimal> Contract_Liability { get; set; }
        public Nullable<decimal> Miscellaneous_Liability { get; set; }
        public Nullable<int> Collateral_Position_ID { get; set; }
        public Nullable<double> Miscellaneous_Exposure_High { get; set; }
        public Nullable<int> Miscellaneous_Exposure_Low_Type_ID { get; set; }
        public Nullable<double> Contract_Exposurehigh { get; set; }
        public Nullable<int> Contract_Exposure_Low_Type_ID { get; set; }
        public Nullable<int> Contract_Exposure_High_Type_ID { get; set; }
        public Nullable<int> Avg_Bond_Term_Factor_High_Exposure_term_ID { get; set; }
        public Nullable<int> Avg_Bond_Term_Factor_Low_Exposure_term_ID { get; set; }
        public Nullable<int> Avg_Bond_Term_Factor_High_Exposure_term1_ID { get; set; }
        public Nullable<int> Avg_Bond_Term_Factor_Low_Exposure_term1_ID { get; set; }
        public Nullable<int> Avg_Bond_Contract_Form_Factor_HighBond_Type_ID { get; set; }
        public Nullable<int> Avg_Bond_Contract_Form_Factor_LowBond_Type_ID { get; set; }
        public Nullable<int> Avg_Bond_Contract_Form_Factor_HighBond1_Type_ID { get; set; }
        public Nullable<int> Avg_Bond_Contract_Form_Factor_LowBond1_Type_ID { get; set; }
        public Nullable<int> Avg_Expense_Factor_High_Bond_Type_ID { get; set; }
        public Nullable<int> Avg_Expense_Factor_Low_Bond_Type_ID { get; set; }
        public Nullable<int> Avg_Expense_Factor_High_Bond1_Type_ID { get; set; }
        public Nullable<int> Avg_Expense_Factor_Low_Bond1_Type_ID { get; set; }
        public Nullable<double> Account_Commission { get; set; }
        public Nullable<int> CommisionType_ID { get; set; }
        public string Class_Code { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> RatingCategoryId { get; set; }
        public Nullable<double> ARMS_Misc_High { get; set; }
        public Nullable<double> ARMS_Misc_Low { get; set; }
        public Nullable<double> ARMS_Contract_High { get; set; }
        public Nullable<double> ARMS_Contract_Low { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public Nullable<bool> IsFinal { get; set; }
        public Nullable<bool> IsMiscHigh { get; set; }
        public Nullable<bool> IsMiscLow { get; set; }
        public Nullable<bool> IsContractHigh { get; set; }
        public Nullable<bool> IsContractLow { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
    }
}
