//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_FinancialBalanceSheet
    {
        public long BalanceSheetID { get; set; }
        public decimal TotalAssets { get; set; }
        public decimal WorkingCapital { get; set; }
        public decimal TotalLiabilitiesnEquity { get; set; }
        public string CurrencyDenomination { get; set; }
        public long StatementID { get; set; }
        public decimal OtherCurrentAssets { get; set; }
        public decimal TotalCurrentAssets { get; set; }
        public decimal OtherLongTermAssets { get; set; }
        public decimal TotalLongTermAssets { get; set; }
        public decimal OtherCurrentLiabilities { get; set; }
        public decimal TotalCurrentLiabilities { get; set; }
        public decimal OtherLongTermLiabilties { get; set; }
        public decimal TotalLongtermLiabilities { get; set; }
        public decimal TotalLiability { get; set; }
        public decimal OtherEquity { get; set; }
        public decimal TotalEquity { get; set; }
        public decimal PrepaidAccruals { get; set; }
        public decimal DeferredTaxes { get; set; }
        public decimal Underbillings { get; set; }
        public decimal Investments { get; set; }
        public decimal Accruals { get; set; }
        public decimal Overbillings { get; set; }
        public decimal Deferrals { get; set; }
        public decimal FitPayable { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ArgAMS_FinancialHeader ArgAMS_FinancialHeader { get; set; }
    }
}
