//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractIndemnityAddlIndemnitor
    {
        public int AddlIndemnitorID { get; set; }
        public string Name { get; set; }
        public int IndemnitorTypeID { get; set; }
        public bool Affiliated { get; set; }
        public Nullable<System.DateTime> LatestFS { get; set; }
        public Nullable<decimal> NetWorth { get; set; }
        public Nullable<decimal> WkgCap { get; set; }
        public int IndemnityID { get; set; }
    
        public virtual ArgAMS_ContractIndemnitorType ArgAMS_ContractIndemnitorType { get; set; }
        public virtual ArgAMS_ContractIndemnity ArgAMS_ContractIndemnity { get; set; }
    }
}
