//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_Set_Control_Property_Mst
    {
        public int Control_Property_ID { get; set; }
        public string On_Action_OF { get; set; }
        public string On_Event { get; set; }
        public string Script_Type { get; set; }
        public string Function_name { get; set; }
        public string Validate_Object { get; set; }
        public string Validate_Property { get; set; }
        public string Validate_Property_Value { get; set; }
        public string Validate_Prop_Datatype { get; set; }
    }
}
