//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_Job
    {
        public int JobID { get; set; }
        public Nullable<int> WIPID { get; set; }
        public Nullable<int> BondID { get; set; }
        public Nullable<decimal> CPPCO { get; set; }
        public Nullable<decimal> OECPCCO { get; set; }
        public Nullable<decimal> BilledToDate { get; set; }
        public Nullable<decimal> CostToDate { get; set; }
        public string JobDescription { get; set; }
    
        public virtual ArgAMS_WIP ArgAMS_WIP { get; set; }
    }
}
