//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractOwnerDetails
    {
        public int OwnerID { get; set; }
        public string OwnerDescription { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public int CreditID { get; set; }
    
        public virtual ArgAMS_ContractCredit ArgAMS_ContractCredit { get; set; }
    }
}
