//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_BondDetail()
        {
            this.ArgAMS_BondClose = new HashSet<ArgAMS_BondClose>();
            this.ArgAMS_BondContractRatePlan = new HashSet<ArgAMS_BondContractRatePlan>();
            this.ArgAMS_BondForm = new HashSet<ArgAMS_BondForm>();
            this.ArgAMS_BondFronting = new HashSet<ArgAMS_BondFronting>();
            this.ArgAMS_BondNonRenewal = new HashSet<ArgAMS_BondNonRenewal>();
            this.ArgAms_BondNotes = new HashSet<ArgAms_BondNotes>();
            this.ArgAMS_BondObligee = new HashSet<ArgAMS_BondObligee>();
            this.ArgAMS_BondPOA = new HashSet<ArgAMS_BondPOA>();
            this.ArgAMS_BondPrincipal = new HashSet<ArgAMS_BondPrincipal>();
            this.ArgAms_BondTaxFee = new HashSet<ArgAms_BondTaxFee>();
            this.ArgAMS_BondTransaction = new HashSet<ArgAMS_BondTransaction>();
            this.ArgAMS_Endorsement = new HashSet<ArgAMS_Endorsement>();
        }
    
        public int BondID { get; set; }
        public string BondNumber { get; set; }
        public string POANumber { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<int> PrincipalID { get; set; }
        public string PrincipalDBA { get; set; }
        public Nullable<int> ObligeeID { get; set; }
        public Nullable<int> ClassCode { get; set; }
        public long AccountID { get; set; }
        public Nullable<decimal> BondAmount { get; set; }
        public Nullable<short> BondTermTypeID { get; set; }
        public Nullable<System.DateTime> BillingEffectiveDate { get; set; }
        public Nullable<System.DateTime> BillingExpirationDate { get; set; }
        public Nullable<short> BillingTypeID { get; set; }
        public Nullable<bool> Cancellable { get; set; }
        public Nullable<int> CancellableDays { get; set; }
        public Nullable<short> PremiumTypeID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> Commisionpercent { get; set; }
        public Nullable<decimal> commisinval { get; set; }
        public Nullable<bool> manualadjust { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<int> BillingNoteID { get; set; }
        public string DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<decimal> AdjustedRate { get; set; }
        public Nullable<decimal> AdjustedPremium { get; set; }
        public Nullable<decimal> PremTobeReturned { get; set; }
        public string AttorneyInFact { get; set; }
        public string OldBondNumber { get; set; }
        public Nullable<System.DateTime> BidDate { get; set; }
        public Nullable<int> ProducerID { get; set; }
        public Nullable<int> CSRID { get; set; }
        public Nullable<decimal> EndorseAmount { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<System.DateTime> EndorseDate { get; set; }
        public Nullable<decimal> SysEndorseAmount { get; set; }
        public Nullable<decimal> SysCancellationAmount { get; set; }
        public string EndorsementReason { get; set; }
        public string AgencyChangeReason { get; set; }
        public Nullable<decimal> TotalTaxandFee { get; set; }
        public Nullable<int> RateCategoryType { get; set; }
        public Nullable<int> BondTypeID { get; set; }
        public string TaxFeeDetail { get; set; }
        public Nullable<int> BondStatusID { get; set; }
        public Nullable<int> BusinessTypeID { get; set; }
        public Nullable<short> IsFederal { get; set; }
        public Nullable<int> UW1 { get; set; }
        public Nullable<bool> CancelAdjust { get; set; }
        public Nullable<int> SubTypeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public byte BondSuffix { get; set; }
        public Nullable<bool> IsProrateOverride { get; set; }
        public Nullable<decimal> EndorsedCommission { get; set; }
        public Nullable<bool> IsContractAmount { get; set; }
        public Nullable<decimal> CompletionSurcharge { get; set; }
        public Nullable<decimal> MaintenanceCharge { get; set; }
        public Nullable<int> ContractRateID { get; set; }
        public Nullable<int> BondIssueTypeID { get; set; }
        public Nullable<System.DateTime> CertDate { get; set; }
        public string CertMailNo { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<decimal> EndorsedTaxfee { get; set; }
        public Nullable<bool> IsReInsurance { get; set; }
        public Nullable<bool> IsQuotaShare { get; set; }
        public Nullable<bool> IsXOL { get; set; }
        public Nullable<bool> IsBulkBill { get; set; }
        public Nullable<System.DateTime> BulkBillStartDate { get; set; }
        public Nullable<System.DateTime> BulkBillEndDate { get; set; }
        public string BulkBillType { get; set; }
        public Nullable<bool> IsInClaim { get; set; }
        public Nullable<int> ClaimStatusId { get; set; }
        public string PermitNumber { get; set; }
        public Nullable<bool> IsDemandLanguage { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string ForeignBondNumber { get; set; }
        public Nullable<int> UWAID { get; set; }
        public string RiskState { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        public virtual ArgAMS_Agency ArgAMS_Agency { get; set; }
        public virtual ArgAMS_BondBillingType ArgAMS_BondBillingType { get; set; }
        public virtual ArgAMS_BondClassCode ArgAMS_BondClassCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondClose> ArgAMS_BondClose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondContractRatePlan> ArgAMS_BondContractRatePlan { get; set; }
        public virtual ArgAMS_BondPremiumType ArgAMS_BondPremiumType { get; set; }
        public virtual ArgAms_BondStatus ArgAms_BondStatus { get; set; }
        public virtual ArgAMS_BondSubType ArgAMS_BondSubType { get; set; }
        public virtual ArgAMS_BondTerm ArgAMS_BondTerm { get; set; }
        public virtual ArgAms_BondStatus ArgAms_BondStatus1 { get; set; }
        public virtual ArgAMS_BondType ArgAMS_BondType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondForm> ArgAMS_BondForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondFronting> ArgAMS_BondFronting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondNonRenewal> ArgAMS_BondNonRenewal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAms_BondNotes> ArgAms_BondNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondObligee> ArgAMS_BondObligee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondPOA> ArgAMS_BondPOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondPrincipal> ArgAMS_BondPrincipal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAms_BondTaxFee> ArgAms_BondTaxFee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_BondTransaction> ArgAMS_BondTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_Endorsement> ArgAMS_Endorsement { get; set; }
    }
}
