//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_AccountTest
    {
        public int AcctID { get; set; }
        public string SICCode { get; set; }
        public string BondNo { get; set; }
        public string AgencyNm { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
