//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondTransaction
    {
        public int BondTransactionID { get; set; }
        public Nullable<int> BondID { get; set; }
        public string BondNumber { get; set; }
        public short BondTransTypeID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public decimal PremiumAmount { get; set; }
        public Nullable<decimal> EndorsedPremium { get; set; }
        public Nullable<System.DateTime> BillingEffectiveDate { get; set; }
        public string NoteDescription { get; set; }
        public Nullable<decimal> TotalTaxandFee { get; set; }
        public string EndorsementReason { get; set; }
        public string AgencyChangeReason { get; set; }
        public string TaxFeeDetail { get; set; }
        public Nullable<decimal> EndorsedAmount { get; set; }
        public Nullable<decimal> EndorsedCommission { get; set; }
        public Nullable<bool> IsBulkBill { get; set; }
        public Nullable<System.DateTime> BulkBillStartDate { get; set; }
        public Nullable<System.DateTime> BulkBillEndDate { get; set; }
        public string BulkBillType { get; set; }
        public Nullable<int> EndorsementId { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> AgencyId { get; set; }
    
        public virtual ArgAMS_BondDetail ArgAMS_BondDetail { get; set; }
        public virtual ArgAMS_BondTransactionType ArgAMS_BondTransactionType { get; set; }
    }
}
