//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_AccountWatchList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_AccountWatchList()
        {
            this.ArgAMS_AccountWatchListActionPlan = new HashSet<ArgAMS_AccountWatchListActionPlan>();
            this.ArgAMS_AccountWatchListActionPlan1 = new HashSet<ArgAMS_AccountWatchListActionPlan>();
        }
    
        public int WatchListID { get; set; }
        public long AccountNumber { get; set; }
        public string ReasonAdded { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> WatchListStatusId { get; set; }
        public Nullable<int> CrewMemberID { get; set; }
        public Nullable<int> AddedById { get; set; }
        public string ReasonRemoved { get; set; }
        public Nullable<int> RemovedById { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
    
        public virtual ArgAMS_AccountWatchListStatus ArgAMS_AccountWatchListStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_AccountWatchListActionPlan> ArgAMS_AccountWatchListActionPlan { get; set; }
        public virtual ArgAMS_AccountWatchListStatus ArgAMS_AccountWatchListStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_AccountWatchListActionPlan> ArgAMS_AccountWatchListActionPlan1 { get; set; }
    }
}
