//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_RateFactor
    {
        public int RateFactorID { get; set; }
        public Nullable<int> RateFactorTypeID { get; set; }
        public string State { get; set; }
        public Nullable<byte> BusinessTypeID { get; set; }
        public Nullable<byte> RateTypeID { get; set; }
        public string ValueText { get; set; }
        public string Value { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> SystemAvailableDate { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    }
}
