//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAms_ContractRatePlanDetails
    {
        public int RatePlanDetailID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<double> BaseRate { get; set; }
        public Nullable<double> FlexFactor { get; set; }
        public Nullable<double> FlexRate { get; set; }
    
        public virtual ArgAMS_ContractRateDetails ArgAMS_ContractRateDetails { get; set; }
    }
}
