//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_CommercialIndemnityData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_CommercialIndemnityData()
        {
            this.ArgAMS_CommercialIndemnitor = new HashSet<ArgAMS_CommercialIndemnitor>();
        }
    
        public int IndemnityID { get; set; }
        public int IndemnityTypeID { get; set; }
        public bool PlaceinFunds { get; set; }
        public int Collateral { get; set; }
        public Nullable<long> NoofDays { get; set; }
        public bool Modifications { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public long AccountNumber { get; set; }
        public Nullable<int> NoteId { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_CommercialIndemnitor> ArgAMS_CommercialIndemnitor { get; set; }
        public virtual ArgAMS_CommercialIndemnityData ArgAMS_CommercialIndemnityData1 { get; set; }
        public virtual ArgAMS_CommercialIndemnityData ArgAMS_CommercialIndemnityData2 { get; set; }
        public virtual ArgAMS_CommercialIndemnityData ArgAMS_CommercialIndemnityData11 { get; set; }
        public virtual ArgAMS_CommercialIndemnityData ArgAMS_CommercialIndemnityData3 { get; set; }
        public virtual ArgAMS_CommercialIndemnityType ArgAMS_CommercialIndemnityType { get; set; }
    }
}
