//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_FinancialCashFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_FinancialCashFlow()
        {
            this.ArgAMS_FinancialCashFlowLineItem = new HashSet<ArgAMS_FinancialCashFlowLineItem>();
        }
    
        public int CashFlowID { get; set; }
        public decimal NetChangeInCash { get; set; }
        public decimal FreeCashFlow { get; set; }
        public Nullable<decimal> NetCashOperatingAct { get; set; }
        public Nullable<decimal> NetCashInvestingAct { get; set; }
        public Nullable<decimal> NetCashFinancingingAct { get; set; }
        public Nullable<long> Statementid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string note { get; set; }
    
        public virtual ArgAMS_FinancialHeader ArgAMS_FinancialHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_FinancialCashFlowLineItem> ArgAMS_FinancialCashFlowLineItem { get; set; }
    }
}
