//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondContractInfo
    {
        public int ContractID { get; set; }
        public Nullable<int> BondID { get; set; }
        public string ContractName { get; set; }
        public string Description { get; set; }
        public System.DateTime ContractEffectiveDate { get; set; }
        public Nullable<System.DateTime> ContractExpirationDate { get; set; }
        public Nullable<int> WarrantyPeriodMonth { get; set; }
        public string BondNumber { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public Nullable<decimal> PerformanceAmount { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<int> MonthsSubjectToSurcharge { get; set; }
        public Nullable<decimal> SurchargePerMonth { get; set; }
        public Nullable<System.DateTime> WarrantyExpireDate { get; set; }
        public Nullable<int> WarrantyPeriodDays { get; set; }
        public string BondForm { get; set; }
    }
}
