//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondForm
    {
        public int BondFormID { get; set; }
        public Nullable<int> BondID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<System.DateTime> DateExecuted { get; set; }
        public Nullable<System.DateTime> DateExecuted1 { get; set; }
        public Nullable<System.DateTime> DateExecuted2 { get; set; }
        public string AttentionTo { get; set; }
        public string AttorneyInFact { get; set; }
        public string DescriptionNote { get; set; }
        public string DescriptionNote1 { get; set; }
        public string RiderChangeFrom { get; set; }
        public string RiderChangeTo { get; set; }
        public string RiderChangeFrom1 { get; set; }
        public string RiderChangeTo1 { get; set; }
        public string RiderChangeFrom2 { get; set; }
        public string RiderChangeTo2 { get; set; }
        public string RiderChangeName2 { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string EmailID { get; set; }
        public string FaxEmail { get; set; }
        public string UWName { get; set; }
        public string UWEmail { get; set; }
    
        public virtual ArgAMS_BondDetail ArgAMS_BondDetail { get; set; }
        public virtual ArgAMS_Form ArgAMS_Form { get; set; }
    }
}
