//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_CoSurety
    {
        public int CoSuretyId { get; set; }
        public string SuretyCompanyName { get; set; }
        public Nullable<decimal> TotalBondAmount { get; set; }
        public Nullable<decimal> ParticipationPercent { get; set; }
        public Nullable<bool> JointSeveral { get; set; }
        public string SideAgreement { get; set; }
        public string SeparateAgreement { get; set; }
        public int BondId { get; set; }
    }
}
