//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_SelfAudit
    {
        public int SelfAuditID { get; set; }
        public Nullable<int> AuditTypeID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> Finalized { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> PriorYearPremium { get; set; }
        public Nullable<int> PrimaryUW { get; set; }
        public Nullable<System.DateTime> AuthorityExpirationDate { get; set; }
        public Nullable<int> BondID { get; set; }
        public string BondNumber { get; set; }
        public Nullable<decimal> WrittenPremium { get; set; }
        public Nullable<System.DateTime> BondEffectiveDate { get; set; }
        public Nullable<System.DateTime> BondExpirationDate { get; set; }
    }
}
