//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_Collateral
    {
        public int CollateralID { get; set; }
        public System.DateTime Date { get; set; }
        public string InstrumentType { get; set; }
        public string InstrumentNumber { get; set; }
        public string Institution { get; set; }
        public decimal Amount { get; set; }
        public Nullable<bool> ReleaseStatus { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public long AccountID { get; set; }
        public Nullable<int> ParentCollateralID { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<int> ChargeType { get; set; }
        public string CollateralNote { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
    }
}
