//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_BondNonRenewal
    {
        public int BondNonRenewalId { get; set; }
        public Nullable<int> BondID { get; set; }
        public string MailCertNumber { get; set; }
        public string AttContact { get; set; }
        public Nullable<System.DateTime> CancelEffectiveDate { get; set; }
        public string AttorneyInFact { get; set; }
        public string OfficeSent { get; set; }
        public Nullable<System.DateTime> DateGenerated { get; set; }
    
        public virtual ArgAMS_BondDetail ArgAMS_BondDetail { get; set; }
    }
}
