//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_AccountWatchListStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_AccountWatchListStatus()
        {
            this.ArgAMS_AccountWatchList = new HashSet<ArgAMS_AccountWatchList>();
            this.ArgAMS_AccountWatchList1 = new HashSet<ArgAMS_AccountWatchList>();
        }
    
        public int WatchListStatusId { get; set; }
        public string WatchStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_AccountWatchList> ArgAMS_AccountWatchList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_AccountWatchList> ArgAMS_AccountWatchList1 { get; set; }
    }
}
