//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_SnPCalculateValue
    {
        public int Calculate_ID { get; set; }
        public Nullable<int> Rates_ID { get; set; }
        public Nullable<double> Total_Debt { get; set; }
        public Nullable<double> Net_Sales { get; set; }
        public Nullable<double> EBIT { get; set; }
        public Nullable<double> Interest_Expense { get; set; }
        public Nullable<double> Operating_Income { get; set; }
        public Nullable<double> Cash_Flow_From_Operations { get; set; }
        public Nullable<double> Capital_Expenditures { get; set; }
        public string SnP_Equivalent { get; set; }
        public Nullable<int> Underwriter_Adjustment_ID { get; set; }
    }
}
