//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractRateDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_ContractRateDetails()
        {
            this.ArgAMS_ContractRateClassCode = new HashSet<ArgAMS_ContractRateClassCode>();
            this.ArgAms_ContractRatePlanDetails = new HashSet<ArgAms_ContractRatePlanDetails>();
        }
    
        public int RateID { get; set; }
        public Nullable<long> AccountID { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public Nullable<int> ClassCodeID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> RefContractRatePlanID { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_ContractRateClassCode> ArgAMS_ContractRateClassCode { get; set; }
        public virtual ArgAMS_Rates_Status ArgAMS_Rates_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAms_ContractRatePlanDetails> ArgAms_ContractRatePlanDetails { get; set; }
    }
}
