//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ContractIndemnityILOC
    {
        public int ILOCID { get; set; }
        public decimal Amount { get; set; }
        public string PostedBy { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> MaturityDt { get; set; }
        public Nullable<System.DateTime> ReleaseDt { get; set; }
        public int IndemnityID { get; set; }
        public Nullable<int> FormTypeId { get; set; }
    
        public virtual ArgAMS_ContractIndemnity ArgAMS_ContractIndemnity { get; set; }
    }
}
