//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_WIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_WIP()
        {
            this.ArgAMS_Job = new HashSet<ArgAMS_Job>();
        }
    
        public int WIPID { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public Nullable<long> AccountID { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_Job> ArgAMS_Job { get; set; }
    }
}
