//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_TaxFee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgAMS_TaxFee()
        {
            this.ArgAms_BondTaxFee = new HashSet<ArgAms_BondTaxFee>();
            this.ArgAMS_TaxFeeState = new HashSet<ArgAMS_TaxFeeState>();
        }
    
        public int TaxFeeID { get; set; }
        public int TaxFeeTypeID { get; set; }
        public string Description { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAms_BondTaxFee> ArgAms_BondTaxFee { get; set; }
        public virtual ArgAMS_TaxFeeType ArgAMS_TaxFeeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgAMS_TaxFeeState> ArgAMS_TaxFeeState { get; set; }
    }
}
