//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_FinancialBalanceSheetLineItem
    {
        public int BSLineItemID { get; set; }
        public int LineItemID { get; set; }
        public decimal Value { get; set; }
        public long BalanceSheetID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> AsGiven { get; set; }
    
        public virtual ArgAMS_FinancialBalanceSheetLineItem ArgAMS_FinancialBalanceSheetLineItem1 { get; set; }
        public virtual ArgAMS_FinancialBalanceSheetLineItem ArgAMS_FinancialBalanceSheetLineItem2 { get; set; }
    }
}
