//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgAMS_ProgramAuth
    {
        public long ProgramAuthID { get; set; }
        public decimal SingleLimit { get; set; }
        public decimal AggregateLimit { get; set; }
        public Nullable<int> GivenToUserID { get; set; }
        public int GivenByUserID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public long AccountNumber { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<byte> Continuous { get; set; }
        public Nullable<byte> Special { get; set; }
        public string GivenToName { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<byte> AAComplete { get; set; }
    
        public virtual ArgAMS_Account ArgAMS_Account { get; set; }
        public virtual ArgAMS_ProgramAuth ArgAMS_ProgramAuth1 { get; set; }
        public virtual ArgAMS_ProgramAuth ArgAMS_ProgramAuth2 { get; set; }
    }
}
