//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArgoSuretyEntities : DbContext
    {
        public ArgoSuretyEntities()
            : base("name=ArgoSuretyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArgAgency_AgencyGroup> ArgAgency_AgencyGroup { get; set; }
        public virtual DbSet<ArgAgency_AgentDetail> ArgAgency_AgentDetail { get; set; }
        public virtual DbSet<ArgAgency_ContactDetail> ArgAgency_ContactDetail { get; set; }
        public virtual DbSet<ArgAgency_Demography> ArgAgency_Demography { get; set; }
        public virtual DbSet<ArgAgency_StatusType> ArgAgency_StatusType { get; set; }
        public virtual DbSet<ArgAgency_TitleType> ArgAgency_TitleType { get; set; }
        public virtual DbSet<ArgAMS_Account> ArgAMS_Account { get; set; }
        public virtual DbSet<ArgAMS_AccountCommercialCredit> ArgAMS_AccountCommercialCredit { get; set; }
        public virtual DbSet<ArgAMS_AccountGroup> ArgAMS_AccountGroup { get; set; }
        public virtual DbSet<ArgAMS_AccountStatus> ArgAMS_AccountStatus { get; set; }
        public virtual DbSet<ArgAMS_AccountWatchList> ArgAMS_AccountWatchList { get; set; }
        public virtual DbSet<ArgAMS_AccountWatchListActionPlan> ArgAMS_AccountWatchListActionPlan { get; set; }
        public virtual DbSet<ArgAMS_AccountWatchListStatus> ArgAMS_AccountWatchListStatus { get; set; }
        public virtual DbSet<ArgAMS_Address> ArgAMS_Address { get; set; }
        public virtual DbSet<ArgAMS_AddressType> ArgAMS_AddressType { get; set; }
        public virtual DbSet<ArgAMS_Agency> ArgAMS_Agency { get; set; }
        public virtual DbSet<ArgAMS_AgencyBORD> ArgAMS_AgencyBORD { get; set; }
        public virtual DbSet<ArgAMS_AgentType> ArgAMS_AgentType { get; set; }
        public virtual DbSet<ArgAMS_BillingType> ArgAMS_BillingType { get; set; }
        public virtual DbSet<ArgAMS_BondBillingType> ArgAMS_BondBillingType { get; set; }
        public virtual DbSet<ArgAMS_BondClassCode> ArgAMS_BondClassCode { get; set; }
        public virtual DbSet<ArgAMS_BondClose> ArgAMS_BondClose { get; set; }
        public virtual DbSet<ArgAMS_BondContractInfo> ArgAMS_BondContractInfo { get; set; }
        public virtual DbSet<ArgAMS_BondContractRatePlan> ArgAMS_BondContractRatePlan { get; set; }
        public virtual DbSet<ArgAMS_BondDetail> ArgAMS_BondDetail { get; set; }
        public virtual DbSet<ArgAMS_BondForm> ArgAMS_BondForm { get; set; }
        public virtual DbSet<ArgAMS_BondFronting> ArgAMS_BondFronting { get; set; }
        public virtual DbSet<ArgAMS_BondFrontingBroker> ArgAMS_BondFrontingBroker { get; set; }
        public virtual DbSet<ArgAMS_BondNonRenewal> ArgAMS_BondNonRenewal { get; set; }
        public virtual DbSet<ArgAms_BondNotes> ArgAms_BondNotes { get; set; }
        public virtual DbSet<ArgAMS_BondNumberAgency> ArgAMS_BondNumberAgency { get; set; }
        public virtual DbSet<ArgAMS_BondObligee> ArgAMS_BondObligee { get; set; }
        public virtual DbSet<ArgAMS_BondPOA> ArgAMS_BondPOA { get; set; }
        public virtual DbSet<ArgAMS_BondPremiumType> ArgAMS_BondPremiumType { get; set; }
        public virtual DbSet<ArgAMS_BondPrincipal> ArgAMS_BondPrincipal { get; set; }
        public virtual DbSet<ArgAms_BondStatus> ArgAms_BondStatus { get; set; }
        public virtual DbSet<ArgAMS_BondSubType> ArgAMS_BondSubType { get; set; }
        public virtual DbSet<ArgAms_BondTaxFee> ArgAms_BondTaxFee { get; set; }
        public virtual DbSet<ArgAMS_BondTerm> ArgAMS_BondTerm { get; set; }
        public virtual DbSet<ArgAMS_BondTransaction> ArgAMS_BondTransaction { get; set; }
        public virtual DbSet<ArgAMS_BondTransactionForeign> ArgAMS_BondTransactionForeign { get; set; }
        public virtual DbSet<ArgAMS_BondTransactionType> ArgAMS_BondTransactionType { get; set; }
        public virtual DbSet<ArgAMS_BondType> ArgAMS_BondType { get; set; }
        public virtual DbSet<ArgAMS_BusinessType> ArgAMS_BusinessType { get; set; }
        public virtual DbSet<ArgAMS_ClassCodeType> ArgAMS_ClassCodeType { get; set; }
        public virtual DbSet<ArgAMS_Collateral> ArgAMS_Collateral { get; set; }
        public virtual DbSet<ArgAMS_CollateralType> ArgAMS_CollateralType { get; set; }
        public virtual DbSet<ArgAMS_CommercialCreditDirection> ArgAMS_CommercialCreditDirection { get; set; }
        public virtual DbSet<ArgAMS_CommercialCreditOutlook> ArgAMS_CommercialCreditOutlook { get; set; }
        public virtual DbSet<ArgAMS_CommercialIndemnitor> ArgAMS_CommercialIndemnitor { get; set; }
        public virtual DbSet<ArgAMS_CommercialIndemnitorType> ArgAMS_CommercialIndemnitorType { get; set; }
        public virtual DbSet<ArgAMS_CommercialIndemnityData> ArgAMS_CommercialIndemnityData { get; set; }
        public virtual DbSet<ArgAMS_CommercialIndemnityType> ArgAMS_CommercialIndemnityType { get; set; }
        public virtual DbSet<ArgAMS_CommercialSystemRatingCategory> ArgAMS_CommercialSystemRatingCategory { get; set; }
        public virtual DbSet<ArgAMS_CommercialSystemRatings> ArgAMS_CommercialSystemRatings { get; set; }
        public virtual DbSet<ArgAMS_ConstOpsTradeAccount> ArgAMS_ConstOpsTradeAccount { get; set; }
        public virtual DbSet<ArgAMS_ContactType> ArgAMS_ContactType { get; set; }
        public virtual DbSet<ArgAMS_ContractConstOps> ArgAMS_ContractConstOps { get; set; }
        public virtual DbSet<ArgAMS_ContractConstOpsExperience> ArgAMS_ContractConstOpsExperience { get; set; }
        public virtual DbSet<ArgAms_ContractConstOpsTrade> ArgAms_ContractConstOpsTrade { get; set; }
        public virtual DbSet<ArgAMS_ContractContinuity> ArgAMS_ContractContinuity { get; set; }
        public virtual DbSet<ArgAMS_ContractCredit> ArgAMS_ContractCredit { get; set; }
        public virtual DbSet<ArgAMS_ContractCreditBankLine> ArgAMS_ContractCreditBankLine { get; set; }
        public virtual DbSet<ArgAms_ContractCreditCompositDBRating> ArgAms_ContractCreditCompositDBRating { get; set; }
        public virtual DbSet<ArgAMS_ContractCreditContinuityType> ArgAMS_ContractCreditContinuityType { get; set; }
        public virtual DbSet<ArgAMS_ContractCreditDBRatings> ArgAMS_ContractCreditDBRatings { get; set; }
        public virtual DbSet<ArgAMS_ContractCreditGurantorList> ArgAMS_ContractCreditGurantorList { get; set; }
        public virtual DbSet<ArgAms_ContractCreditRateType> ArgAms_ContractCreditRateType { get; set; }
        public virtual DbSet<ArgAMS_ContractCreditSecuritylist> ArgAMS_ContractCreditSecuritylist { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnitors> ArgAMS_ContractIndemnitors { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnitorType> ArgAMS_ContractIndemnitorType { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnity> ArgAMS_ContractIndemnity { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnityAddlIndemnitor> ArgAMS_ContractIndemnityAddlIndemnitor { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnityAgreementType> ArgAMS_ContractIndemnityAgreementType { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnityILOC> ArgAMS_ContractIndemnityILOC { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnitySubOrdination> ArgAMS_ContractIndemnitySubOrdination { get; set; }
        public virtual DbSet<ArgAMS_ContractIndemnityType> ArgAMS_ContractIndemnityType { get; set; }
        public virtual DbSet<ArgAMS_ContractModificationType> ArgAMS_ContractModificationType { get; set; }
        public virtual DbSet<ArgAMS_ContractOwnerDetails> ArgAMS_ContractOwnerDetails { get; set; }
        public virtual DbSet<ArgAMS_ContractRateClassCode> ArgAMS_ContractRateClassCode { get; set; }
        public virtual DbSet<ArgAMS_ContractRateDetails> ArgAMS_ContractRateDetails { get; set; }
        public virtual DbSet<ArgAMS_ContractRatePlan> ArgAMS_ContractRatePlan { get; set; }
        public virtual DbSet<ArgAms_ContractRatePlanDetails> ArgAms_ContractRatePlanDetails { get; set; }
        public virtual DbSet<ArgAms_ContractRateStep> ArgAms_ContractRateStep { get; set; }
        public virtual DbSet<ArgAMS_ContractRateType> ArgAMS_ContractRateType { get; set; }
        public virtual DbSet<ArgAMS_CoSurety> ArgAMS_CoSurety { get; set; }
        public virtual DbSet<ArgAMS_Country> ArgAMS_Country { get; set; }
        public virtual DbSet<ArgAMS_Endorsement> ArgAMS_Endorsement { get; set; }
        public virtual DbSet<ArgAms_EndorsementType> ArgAms_EndorsementType { get; set; }
        public virtual DbSet<ArgAMS_Exchange> ArgAMS_Exchange { get; set; }
        public virtual DbSet<ArgAMS_Factor_Type_Mst> ArgAMS_Factor_Type_Mst { get; set; }
        public virtual DbSet<ArgAMS_FinancialBalanceSheet> ArgAMS_FinancialBalanceSheet { get; set; }
        public virtual DbSet<ArgAMS_FinancialBalanceSheetLineItem> ArgAMS_FinancialBalanceSheetLineItem { get; set; }
        public virtual DbSet<ArgAMS_FinancialBusinessType> ArgAMS_FinancialBusinessType { get; set; }
        public virtual DbSet<ArgAMS_FinancialCashFlow> ArgAMS_FinancialCashFlow { get; set; }
        public virtual DbSet<ArgAMS_FinancialCashFlowLineItem> ArgAMS_FinancialCashFlowLineItem { get; set; }
        public virtual DbSet<ArgAMS_FinancialHeader> ArgAMS_FinancialHeader { get; set; }
        public virtual DbSet<ArgAMS_FinancialIncomeStatementLineItem> ArgAMS_FinancialIncomeStatementLineItem { get; set; }
        public virtual DbSet<ArgAMS_FinancialLineItemAccount> ArgAMS_FinancialLineItemAccount { get; set; }
        public virtual DbSet<ArgAMS_FinancialPeriodType> ArgAMS_FinancialPeriodType { get; set; }
        public virtual DbSet<ArgAMS_FinancialSectionType> ArgAMS_FinancialSectionType { get; set; }
        public virtual DbSet<ArgAMS_Form> ArgAMS_Form { get; set; }
        public virtual DbSet<ArgAMS_InClaimStatus> ArgAMS_InClaimStatus { get; set; }
        public virtual DbSet<ArgAMS_InvoiceErrorDetail> ArgAMS_InvoiceErrorDetail { get; set; }
        public virtual DbSet<ArgAMS_Job> ArgAMS_Job { get; set; }
        public virtual DbSet<ArgAMS_Location> ArgAMS_Location { get; set; }
        public virtual DbSet<ArgAMS_Note> ArgAMS_Note { get; set; }
        public virtual DbSet<ArgAMS_NoteType> ArgAMS_NoteType { get; set; }
        public virtual DbSet<ArgAMS_Obligee> ArgAMS_Obligee { get; set; }
        public virtual DbSet<ArgAMS_POAAgency> ArgAMS_POAAgency { get; set; }
        public virtual DbSet<ArgAMS_Principal> ArgAMS_Principal { get; set; }
        public virtual DbSet<ArgAMS_PrincipalType> ArgAMS_PrincipalType { get; set; }
        public virtual DbSet<ArgAMS_PriorSurety> ArgAMS_PriorSurety { get; set; }
        public virtual DbSet<ArgAMS_PrivateEquityOwnedList> ArgAMS_PrivateEquityOwnedList { get; set; }
        public virtual DbSet<ArgAMS_ProgramAuth> ArgAMS_ProgramAuth { get; set; }
        public virtual DbSet<ArgAMS_RateCalculator> ArgAMS_RateCalculator { get; set; }
        public virtual DbSet<ArgAMS_RateClassCode> ArgAMS_RateClassCode { get; set; }
        public virtual DbSet<ArgAMS_RateDetail> ArgAMS_RateDetail { get; set; }
        public virtual DbSet<ArgAMS_RateFactor> ArgAMS_RateFactor { get; set; }
        public virtual DbSet<ArgAMS_RateFactorType> ArgAMS_RateFactorType { get; set; }
        public virtual DbSet<ArgAMS_Rates_Details> ArgAMS_Rates_Details { get; set; }
        public virtual DbSet<ArgAMS_Rates_Status> ArgAMS_Rates_Status { get; set; }
        public virtual DbSet<ArgAMS_RateStateType> ArgAMS_RateStateType { get; set; }
        public virtual DbSet<ArgAMS_RateStructure> ArgAMS_RateStructure { get; set; }
        public virtual DbSet<ArgAMS_Region> ArgAMS_Region { get; set; }
        public virtual DbSet<ArgAMS_SAAClassCode> ArgAMS_SAAClassCode { get; set; }
        public virtual DbSet<ArgAMS_SelfAudit> ArgAMS_SelfAudit { get; set; }
        public virtual DbSet<ArgAMS_SelfAuditAnswers> ArgAMS_SelfAuditAnswers { get; set; }
        public virtual DbSet<ArgAMS_SelfAuditQuestion> ArgAMS_SelfAuditQuestion { get; set; }
        public virtual DbSet<ArgAMS_SelfAuditType> ArgAMS_SelfAuditType { get; set; }
        public virtual DbSet<ArgAMS_Set_Control_Property_Mst> ArgAMS_Set_Control_Property_Mst { get; set; }
        public virtual DbSet<ArgAMS_SICCodeIndustryType> ArgAMS_SICCodeIndustryType { get; set; }
        public virtual DbSet<ArgAMS_StatusReason> ArgAMS_StatusReason { get; set; }
        public virtual DbSet<ArgAMS_TaxFee> ArgAMS_TaxFee { get; set; }
        public virtual DbSet<ArgAMS_TaxFeeState> ArgAMS_TaxFeeState { get; set; }
        public virtual DbSet<ArgAMS_TaxFeeType> ArgAMS_TaxFeeType { get; set; }
        public virtual DbSet<ArgAMS_WIP> ArgAMS_WIP { get; set; }
        public virtual DbSet<ArgAMS_WIPData> ArgAMS_WIPData { get; set; }
        public virtual DbSet<ArgGCIS_PolicyBond> ArgGCIS_PolicyBond { get; set; }
        public virtual DbSet<ArgPOA_Client> ArgPOA_Client { get; set; }
        public virtual DbSet<ArgPOA_PrintData> ArgPOA_PrintData { get; set; }
        public virtual DbSet<ArgSec_AccessType> ArgSec_AccessType { get; set; }
        public virtual DbSet<ArgSec_Level> ArgSec_Level { get; set; }
        public virtual DbSet<ArgSec_Module> ArgSec_Module { get; set; }
        public virtual DbSet<ArgSec_Role> ArgSec_Role { get; set; }
        public virtual DbSet<ArgSec_RoleModule> ArgSec_RoleModule { get; set; }
        public virtual DbSet<ArgSec_RoleScreen> ArgSec_RoleScreen { get; set; }
        public virtual DbSet<ArgSec_Screen> ArgSec_Screen { get; set; }
        public virtual DbSet<ArgSec_ScreenControls> ArgSec_ScreenControls { get; set; }
        public virtual DbSet<ArgSec_ScreenModule> ArgSec_ScreenModule { get; set; }
        public virtual DbSet<ArgSec_SecretQuestion> ArgSec_SecretQuestion { get; set; }
        public virtual DbSet<ArgSec_SystemLock> ArgSec_SystemLock { get; set; }
        public virtual DbSet<ArgSec_User> ArgSec_User { get; set; }
        public virtual DbSet<ArgSec_UserLog> ArgSec_UserLog { get; set; }
        public virtual DbSet<ArgSec_UserPasswordHistory> ArgSec_UserPasswordHistory { get; set; }
        public virtual DbSet<ArgSec_UserRole> ArgSec_UserRole { get; set; }
        public virtual DbSet<ArgSec_UserScreen> ArgSec_UserScreen { get; set; }
        public virtual DbSet<ArgAgency_Notes> ArgAgency_Notes { get; set; }
        public virtual DbSet<argams_account_backup_20111209> argams_account_backup_20111209 { get; set; }
        public virtual DbSet<ArgAMS_Account_fix> ArgAMS_Account_fix { get; set; }
        public virtual DbSet<ArgAMS_AccountTest> ArgAMS_AccountTest { get; set; }
        public virtual DbSet<ArgAMS_ARMS_Details> ArgAMS_ARMS_Details { get; set; }
        public virtual DbSet<ArgAMS_ARMS_Limits> ArgAMS_ARMS_Limits { get; set; }
        public virtual DbSet<ArgAMS_ARMS_Risk_Char_GRP_MST> ArgAMS_ARMS_Risk_Char_GRP_MST { get; set; }
        public virtual DbSet<ArgAMS_ARMS_Risks_Sub_MST> ArgAMS_ARMS_Risks_Sub_MST { get; set; }
        public virtual DbSet<ArgAMS_BondIssueType> ArgAMS_BondIssueType { get; set; }
        public virtual DbSet<ArgAMS_CollateralTransactionType> ArgAMS_CollateralTransactionType { get; set; }
        public virtual DbSet<ArgAMS_Company_Type_Mst> ArgAMS_Company_Type_Mst { get; set; }
        public virtual DbSet<ArgAMS_ContractFormType> ArgAMS_ContractFormType { get; set; }
        public virtual DbSet<ArgAMS_Factor_Details> ArgAMS_Factor_Details { get; set; }
        public virtual DbSet<ArgAMS_FinancialLineItem> ArgAMS_FinancialLineItem { get; set; }
        public virtual DbSet<ArgAMS_FinancialStatementType> ArgAMS_FinancialStatementType { get; set; }
        public virtual DbSet<ArgAMS_Global_Calc_Values> ArgAMS_Global_Calc_Values { get; set; }
        public virtual DbSet<ArgAMS_ProducerCSR> ArgAMS_ProducerCSR { get; set; }
        public virtual DbSet<ArgAMS_ProgramAuthHistory> ArgAMS_ProgramAuthHistory { get; set; }
        public virtual DbSet<ArgAMS_RateSnPEquivalent> ArgAMS_RateSnPEquivalent { get; set; }
        public virtual DbSet<ArgAMS_RatesSnPMoodyRating> ArgAMS_RatesSnPMoodyRating { get; set; }
        public virtual DbSet<ArgAMS_SICode> ArgAMS_SICode { get; set; }
        public virtual DbSet<ArgAMS_SnP_Equivalent_Rating_Mst> ArgAMS_SnP_Equivalent_Rating_Mst { get; set; }
        public virtual DbSet<ArgAMS_SnPCalculateValue> ArgAMS_SnPCalculateValue { get; set; }
        public virtual DbSet<ArgAMS_USZipList> ArgAMS_USZipList { get; set; }
        public virtual DbSet<ArgPOA_Company> ArgPOA_Company { get; set; }
        public virtual DbSet<ArgPOA_State> ArgPOA_State { get; set; }
        public virtual DbSet<ArgSec_Permission> ArgSec_Permission { get; set; }
        public virtual DbSet<ArgSec_Temp_AccessType> ArgSec_Temp_AccessType { get; set; }
        public virtual DbSet<ArgSec_Temp_Screen> ArgSec_Temp_Screen { get; set; }
        public virtual DbSet<ArgSec_temp_ScreenControls> ArgSec_temp_ScreenControls { get; set; }
        public virtual DbSet<ArgAMS_AccountFactsetSecurity> ArgAMS_AccountFactsetSecurity { get; set; }
    }
}
