//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgPOA_Company
    {
        public int CompanyID { get; set; }
        public string CompanyAbbr { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyState { get; set; }
        public string CompanyZip { get; set; }
        public string CompanyCounty { get; set; }
        public string CompanySig1Name { get; set; }
        public string CompanySig1Title { get; set; }
        public byte[] CompanySig1Image { get; set; }
        public string CompanySig2Name { get; set; }
        public string CompanySig2Title { get; set; }
        public byte[] CompanySig2Image { get; set; }
        public byte[] CompanyNotaryStamp { get; set; }
        public byte[] CompanyNotaryImage { get; set; }
        public string CompanyNotaryCounty { get; set; }
        public string CompanyNotaryState { get; set; }
    }
}
