//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgPOA_PrintData
    {
        public int Id { get; set; }
        public string PrintID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> FirstPrintDate { get; set; }
        public Nullable<System.DateTime> LastPrintDate { get; set; }
        public string PrinterInitials { get; set; }
        public string Status { get; set; }
        public Nullable<bool> vFlag { get; set; }
        public Nullable<bool> bFlag { get; set; }
    }
}
