//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgSec_UserPasswordHistory
    {
        public long UserPasswordHistoryID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    }
}
