//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgSec_Temp_Screen
    {
        public int ScreenID { get; set; }
        public string ScreenName { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string TokenString { get; set; }
        public Nullable<byte> SortIndex { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
