//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgSec_UserRole
    {
        public int RoleID { get; set; }
        public int UserID { get; set; }
        public int UserRoleID { get; set; }
    
        public virtual ArgSec_Role ArgSec_Role { get; set; }
        public virtual ArgSec_User ArgSec_User { get; set; }
    }
}
