//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgSec_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgSec_User()
        {
            this.ArgSec_SystemLock = new HashSet<ArgSec_SystemLock>();
            this.ArgSec_UserRole = new HashSet<ArgSec_UserRole>();
            this.ArgSec_UserScreen = new HashSet<ArgSec_UserScreen>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecretQuestion { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Answer { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<short> LoginAttempts { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<decimal> AuthLimit { get; set; }
        public Nullable<decimal> AggregateLimit { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public Nullable<bool> IsWLApprover { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgSec_SystemLock> ArgSec_SystemLock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgSec_UserRole> ArgSec_UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgSec_UserScreen> ArgSec_UserScreen { get; set; }
    }
}
