//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgSec_temp_ScreenControls
    {
        public int ScreenControlsID { get; set; }
        public Nullable<int> Screen_ID { get; set; }
        public string AddControl { get; set; }
        public string EditControl { get; set; }
        public string DeleteControl { get; set; }
        public string EndorseControl { get; set; }
        public Nullable<bool> HasControls { get; set; }
        public string AddPage { get; set; }
        public string EditPage { get; set; }
        public string DeletePage { get; set; }
    }
}
