//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ce_fiscal_period_map
    {
        public string fiscal_period_code { get; set; }
        public string fiscal_period_display_name { get; set; }
        public string fiscal_period_desc { get; set; }
    }
}
