//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class cic_classification_map
    {
        public string cic_code { get; set; }
        public string cic_category { get; set; }
        public string cic_category_desc { get; set; }
        public string cic_sub_category { get; set; }
        public string cic_sub_category_desc { get; set; }
    }
}
