//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class econ_country_inclusion
    {
        public string iso_country { get; set; }
        public short bric { get; set; }
        public short developed { get; set; }
        public short emerging { get; set; }
        public short eu15 { get; set; }
        public short eu27 { get; set; }
        public short eurozone { get; set; }
        public short g20 { get; set; }
        public short g7 { get; set; }
        public short gcc { get; set; }
        public short giips { get; set; }
        public short opec { get; set; }
        public short asean { get; set; }
    }
}
