//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ent_entity_address
    {
        public long ID { get; set; }
        public string ADDRESS_ID { get; set; }
        public string FACTSET_ENTITY_ID { get; set; }
        public string LOCATION_CITY { get; set; }
        public string STATE_PROVINCE { get; set; }
        public string LOCATION_POSTAL_CODE { get; set; }
        public string CITY_STATE_ZIP { get; set; }
        public string LOCATION_STREET1 { get; set; }
        public string LOCATION_STREET2 { get; set; }
        public string LOCATION_STREET3 { get; set; }
        public string ISO_COUNTRY { get; set; }
        public string TELE_COUNTRY { get; set; }
        public string TELE_AREA { get; set; }
        public string TELE { get; set; }
        public string TELE_FULL { get; set; }
        public string FAX_COUNTRY { get; set; }
        public string FAX_AREA { get; set; }
        public string FAX { get; set; }
        public string FAX_FULL { get; set; }
        public string HQ { get; set; }
    }
}
