//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDS_FILE_HISTORY
    {
        public int id { get; set; }
        public int zh_id { get; set; }
        public string table_name { get; set; }
        public string bundle { get; set; }
        public string text_file { get; set; }
        public int sequence { get; set; }
        public string file_type { get; set; }
        public short split { get; set; }
        public short success { get; set; }
        public Nullable<double> extract_seconds { get; set; }
        public Nullable<double> move_seconds { get; set; }
        public Nullable<double> load_seconds { get; set; }
        public Nullable<int> data_rows { get; set; }
        public Nullable<long> file_bytes { get; set; }
        public System.DateTime begin_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
    }
}
