//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDS_ZIP_HISTORY
    {
        public int id { get; set; }
        public int ch_id { get; set; }
        public string bundle { get; set; }
        public string zip_type { get; set; }
        public int sequence { get; set; }
        public short success { get; set; }
        public Nullable<double> download_seconds { get; set; }
        public Nullable<long> zip_bytes { get; set; }
        public System.DateTime begin_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
    }
}
