//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDS_DATA_SEQUENCES
    {
        public string schema_name { get; set; }
        public string table_name { get; set; }
        public string bundle { get; set; }
        public string text_file { get; set; }
        public int sequence { get; set; }
        public string last_physical_full { get; set; }
        public string last_physical_delete { get; set; }
        public string last_physical_update { get; set; }
        public string last_physical_fast { get; set; }
    }
}
