//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class fe_item_map
    {
        public string fe_item { get; set; }
        public string fe_item_desc { get; set; }
        public string fe_ind_desc { get; set; }
        public string units { get; set; }
        public short hasquarter { get; set; }
        public short hasfiscalyear { get; set; }
        public short hasactual { get; set; }
        public short hasactualonly { get; set; }
    }
}
