//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class fe_item
    {
        public string fe_item1 { get; set; }
        public Nullable<short> currind { get; set; }
        public string splitind { get; set; }
        public double unitfactor { get; set; }
        public string factcode { get; set; }
        public Nullable<short> hasquarter { get; set; }
        public Nullable<short> hasfiscalyear { get; set; }
        public Nullable<short> hasactual { get; set; }
        public Nullable<short> hasactualonly { get; set; }
        public string name { get; set; }
        public string fe_ind { get; set; }
        public string units { get; set; }
    }
}
