//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_advanced_der_ltm_v2
    {
        public string fs_perm_sec_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> adjdate { get; set; }
        public string currency { get; set; }
        public Nullable<double> ff_capex_5ygr { get; set; }
        public Nullable<double> ff_capex_ps_cf { get; set; }
        public Nullable<double> ff_cash_div_cf { get; set; }
        public Nullable<double> ff_cash_div_covg_ratio { get; set; }
        public Nullable<double> ff_cf_sales { get; set; }
        public Nullable<double> ff_cogs_sales { get; set; }
        public Nullable<double> ff_debt_lt_cf { get; set; }
        public Nullable<double> ff_dil_adj { get; set; }
        public Nullable<double> ff_ebit_oper_mgn { get; set; }
        public Nullable<double> ff_ebitda_cf { get; set; }
        public Nullable<double> ff_ebitda_oper_mgn { get; set; }
        public Nullable<double> ff_eps_basic_gr { get; set; }
        public Nullable<double> ff_free_ps_cf { get; set; }
        public Nullable<double> ff_inc_adj { get; set; }
        public Nullable<double> ff_int_exp_oth { get; set; }
        public Nullable<double> ff_loss_ratio { get; set; }
        public Nullable<double> ff_net_inc_basic_aft_xord { get; set; }
        public Nullable<double> ff_net_inc_basic_beft_xord { get; set; }
        public Nullable<double> ff_net_inc_bef_xord_gr { get; set; }
        public Nullable<double> ff_net_inc_dil { get; set; }
        public Nullable<double> ff_net_inc_dil_aft_xord { get; set; }
        public Nullable<double> ff_net_mgn_gr { get; set; }
        public Nullable<double> ff_non_int_inc_rev { get; set; }
        public Nullable<double> ff_oper_cf_fix_chrg { get; set; }
        public Nullable<double> ff_oper_inc_aft_unusual { get; set; }
        public Nullable<double> ff_oper_inc_gr { get; set; }
        public Nullable<double> ff_oper_inc_prem_earn { get; set; }
        public Nullable<double> ff_oper_ps_net_cf { get; set; }
        public Nullable<double> ff_rd_sales { get; set; }
        public Nullable<double> ff_sales_gr { get; set; }
        public Nullable<double> ff_sales_ps_gr { get; set; }
        public Nullable<double> ff_sga_oth { get; set; }
        public Nullable<double> ff_sga_sales { get; set; }
        public Nullable<double> ff_spec_items { get; set; }
        public Nullable<double> ff_tax_rate { get; set; }
        public Nullable<double> ff_ut_gross_inc { get; set; }
        public Nullable<double> ff_ut_operation_exp { get; set; }
        public Nullable<double> ff_xord { get; set; }
        public Nullable<double> ff_xord_disc { get; set; }
        public Nullable<double> ff_ebit_bef_unusual { get; set; }
        public Nullable<double> ff_ebitda_bef_unusual { get; set; }
        public Nullable<double> ff_eps_dil_aft_xord { get; set; }
        public Nullable<double> ff_net_inc_dil_bef_unusual { get; set; }
        public Nullable<double> ff_int_inc_misc { get; set; }
    }
}
