//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_advanced_ltm_v2
    {
        public string fs_perm_sec_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> adjdate { get; set; }
        public string currency { get; set; }
        public Nullable<double> ff_accr_exp_cf { get; set; }
        public Nullable<double> ff_amort_cf { get; set; }
        public Nullable<double> ff_commiss_inc { get; set; }
        public Nullable<double> ff_dep_exp_uncon { get; set; }
        public Nullable<double> ff_dep_exp_xamort_cf { get; set; }
        public Nullable<double> ff_dfd_tax_xitc_cf { get; set; }
        public Nullable<double> ff_disc_oper_inc { get; set; }
        public Nullable<double> ff_eps { get; set; }
        public Nullable<double> ff_eps_contin_oper { get; set; }
        public Nullable<double> ff_eps_secs { get; set; }
        public Nullable<double> ff_eps_uncon { get; set; }
        public Nullable<double> ff_eps_xord { get; set; }
        public Nullable<double> ff_equip_exp { get; set; }
        public Nullable<double> ff_for_curn_adj { get; set; }
        public Nullable<double> ff_gain_sale_assets_net { get; set; }
        public Nullable<double> ff_ins_invest_inc { get; set; }
        public Nullable<double> ff_ins_lt_rsrv { get; set; }
        public Nullable<double> ff_int_exp_deps { get; set; }
        public Nullable<double> ff_int_exp_fed_repos { get; set; }
        public Nullable<double> ff_int_exp_oth_borr { get; set; }
        public Nullable<double> ff_int_inc_deps { get; set; }
        public Nullable<double> ff_int_inc_fed_funds { get; set; }
        public Nullable<double> ff_int_inc_loan { get; set; }
        public Nullable<double> ff_int_inc_oth { get; set; }
        public Nullable<double> ff_inven_cf { get; set; }
        public Nullable<double> ff_invest_inc { get; set; }
        public Nullable<double> ff_labor_exp { get; set; }
        public Nullable<double> ff_oper_exp { get; set; }
        public Nullable<double> ff_oper_inc_bef_dep { get; set; }
        public Nullable<double> ff_opt_wrnt_cf { get; set; }
        public Nullable<double> ff_pay_acct_cf { get; set; }
        public Nullable<double> ff_pay_tax_cf { get; set; }
        public Nullable<double> ff_real_gain { get; set; }
        public Nullable<double> ff_receiv_cf { get; set; }
        public Nullable<double> ff_secs_gain { get; set; }
        public Nullable<double> ff_stk_sale_xopt_cf { get; set; }
        public Nullable<double> ff_tax_non_inc { get; set; }
        public Nullable<double> ff_trade_inc { get; set; }
        public Nullable<double> ff_trust_inc { get; set; }
        public Nullable<double> ff_wkcap_assets_oth { get; set; }
        public Nullable<double> ff_fix_assets_impair { get; set; }
        public Nullable<double> ff_gw_impair { get; set; }
        public Nullable<double> ff_intang_oth_impair { get; set; }
        public Nullable<double> ff_ppe_impair { get; set; }
        public Nullable<double> ff_tax_cf { get; set; }
        public Nullable<double> ff_actg_chg { get; set; }
        public Nullable<double> ff_int_cf { get; set; }
        public Nullable<double> ff_disc_oper { get; set; }
        public Nullable<double> ff_eq_aff_inc_ptx { get; set; }
        public Nullable<double> ff_misc_exp_non_oper { get; set; }
        public Nullable<double> ff_int_exp_debt { get; set; }
        public Nullable<double> ff_xord_items { get; set; }
        public Nullable<double> ff_invest_sale_cf { get; set; }
        public Nullable<double> ff_div_com_cf { get; set; }
        public Nullable<double> ff_stk_purch_cf { get; set; }
        public Nullable<double> ff_stk_sale_cf { get; set; }
        public Nullable<double> ff_debt_st_cf { get; set; }
        public Nullable<double> ff_capex_fix { get; set; }
        public Nullable<double> ff_capex_oth { get; set; }
        public Nullable<double> ff_debt_lt_iss_cf { get; set; }
        public Nullable<double> ff_debt_lt_reduct_cf { get; set; }
        public Nullable<double> ff_fin_uses_cf { get; set; }
        public Nullable<double> ff_fin_sources_cf { get; set; }
        public Nullable<double> ff_invest_purch_cf { get; set; }
        public Nullable<double> ff_cogs_xdep { get; set; }
        public Nullable<double> ff_dep_amort_exp { get; set; }
        public Nullable<double> ff_rd_exp { get; set; }
        public Nullable<double> ff_oper_inc_oth { get; set; }
        public Nullable<double> ff_ordinary_inc { get; set; }
        public Nullable<double> ff_loss_claim_exp { get; set; }
        public Nullable<double> ff_prem_earn { get; set; }
        public Nullable<double> ff_underwriting_exp { get; set; }
    }
}
