//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_basic_der_ltm_v2
    {
        public string fs_perm_sec_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> adjdate { get; set; }
        public string currency { get; set; }
        public Nullable<double> ff_cogs { get; set; }
        public Nullable<double> ff_unusual_exp { get; set; }
        public Nullable<double> ff_int_exp_net { get; set; }
        public Nullable<double> ff_net_inc { get; set; }
        public Nullable<double> ff_net_inc_basic { get; set; }
        public Nullable<double> ff_int_inc_aft_prov { get; set; }
        public Nullable<double> ff_loss_claim_rsrv { get; set; }
        public Nullable<double> ff_sga_oth_exp { get; set; }
        public Nullable<double> ff_oper_inc_bef_int { get; set; }
        public Nullable<double> ff_oper_cf { get; set; }
        public Nullable<double> ff_capex { get; set; }
        public Nullable<double> ff_invest_purch_sale_cf { get; set; }
        public Nullable<double> ff_invest_uses_cf { get; set; }
        public Nullable<double> ff_invest_cf { get; set; }
        public Nullable<double> ff_stk_chg_cf { get; set; }
        public Nullable<double> ff_debt_cf { get; set; }
        public Nullable<double> ff_fin_activ_oth_cf { get; set; }
        public Nullable<double> ff_fin_cf { get; set; }
        public Nullable<double> ff_misc_funds_cf { get; set; }
        public Nullable<double> ff_free_cf { get; set; }
        public Nullable<double> ff_eps_dil_bef_unusual { get; set; }
        public Nullable<double> ff_capex_sales { get; set; }
        public Nullable<double> ff_ebitda_oper { get; set; }
        public Nullable<double> ff_gross_mgn { get; set; }
        public Nullable<double> ff_net_mgn { get; set; }
        public Nullable<double> ff_oper_mgn { get; set; }
        public Nullable<double> ff_ptx_mgn { get; set; }
        public Nullable<double> ff_int_inc_net { get; set; }
        public Nullable<double> ff_eps_dil { get; set; }
        public Nullable<double> ff_sga { get; set; }
        public Nullable<double> ff_sales_ps { get; set; }
        public Nullable<double> ff_ebit_oper { get; set; }
        public Nullable<double> ff_net_inc_aft_xord { get; set; }
    }
}
