//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_basic_v2
    {
        public string fs_perm_sec_id { get; set; }
        public string factset_entity_id { get; set; }
        public string currency { get; set; }
        public string ff_country_iso { get; set; }
        public string fa_countryn { get; set; }
        public short fa_iscomp { get; set; }
        public string fa_ads_exch_rate { get; set; }
        public Nullable<decimal> fa_latest_ann_update { get; set; }
        public string ff_co_name { get; set; }
        public string ff_bus_desc_abbrev { get; set; }
        public short universe_am { get; set; }
        public short universe_eu { get; set; }
        public short universe_ap { get; set; }
        public Nullable<int> ff_gen_ind { get; set; }
        public short ff_compact { get; set; }
        public Nullable<double> ff_mkt_val_curr { get; set; }
        public Nullable<double> ff_curr_ps_cf { get; set; }
        public string ff_email_invest_rel { get; set; }
        public string ff_name_invest_rel { get; set; }
        public string ff_phone_invest_rel { get; set; }
        public Nullable<short> ff_is_adr { get; set; }
        public short ff_secact { get; set; }
        public string ff_share_type_secs { get; set; }
        public Nullable<double> ff_dps_ltm_secs { get; set; }
        public Nullable<double> ff_pbk_secs_curr { get; set; }
        public Nullable<double> ff_div_yld_curr { get; set; }
        public Nullable<double> ff_div_pay_out_ps_curr { get; set; }
        public Nullable<double> ff_pe_secs_curr { get; set; }
        public short ff_is_dually_listed { get; set; }
        public short ff_is_multi_share { get; set; }
        public Nullable<double> ff_shs_repurch { get; set; }
    }
}
