//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_balance_model
    {
        public string report_code { get; set; }
        public int display_order { get; set; }
        public string display_level { get; set; }
        public string field_name { get; set; }
        public string description { get; set; }
        public short negative { get; set; }
        public short basic { get; set; }
        public short advanced { get; set; }
        public short ann { get; set; }
        public short qtr { get; set; }
        public short semi { get; set; }
        public short ltm { get; set; }
        public short supplemental { get; set; }
    }
}
