//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_balance_model_ind
    {
        public string field_name { get; set; }
        public string description { get; set; }
        public short ind { get; set; }
        public short bank { get; set; }
        public short ins { get; set; }
        public short oth { get; set; }
        public short pen { get; set; }
        public short basic { get; set; }
        public short advanced { get; set; }
        public short ann { get; set; }
        public short qtr { get; set; }
        public short semi { get; set; }
        public short ltm { get; set; }
    }
}
