//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_basic_qf_v2
    {
        public string fs_perm_sec_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> adjdate { get; set; }
        public string currency { get; set; }
        public decimal ff_fpnc { get; set; }
        public string ff_upd_type { get; set; }
        public string ff_coverage { get; set; }
        public Nullable<double> ff_sales { get; set; }
        public Nullable<double> ff_int_inc { get; set; }
        public Nullable<double> ff_non_int_inc { get; set; }
        public Nullable<double> ff_gross_inc { get; set; }
        public Nullable<double> ff_oper_exp_oth { get; set; }
        public Nullable<double> ff_oper_exp_tot { get; set; }
        public Nullable<double> ff_oper_inc { get; set; }
        public Nullable<double> ff_int_exp_tot { get; set; }
        public Nullable<double> ff_loan_loss_prov { get; set; }
        public Nullable<double> ff_non_int_exp { get; set; }
        public Nullable<double> ff_ptx_xord_chrg { get; set; }
        public Nullable<double> ff_ptx_xord_cr { get; set; }
        public Nullable<double> ff_ptx_inc { get; set; }
        public Nullable<double> ff_inc_tax { get; set; }
        public Nullable<double> ff_min_int_exp { get; set; }
        public Nullable<double> ff_eq_aff_inc { get; set; }
        public Nullable<double> ff_net_income { get; set; }
        public Nullable<double> ff_div_pfd { get; set; }
        public Nullable<double> ff_cash_st { get; set; }
        public Nullable<double> ff_cash_only { get; set; }
        public Nullable<double> ff_cash_due_fr_bk { get; set; }
        public Nullable<double> ff_bk_invest_tot { get; set; }
        public Nullable<double> ff_receiv_tot { get; set; }
        public Nullable<double> ff_inven { get; set; }
        public Nullable<double> ff_assets_curr { get; set; }
        public Nullable<double> ff_assets_oth_intang { get; set; }
        public Nullable<double> ff_intang { get; set; }
        public Nullable<double> ff_assets { get; set; }
        public Nullable<double> ff_deps { get; set; }
        public Nullable<double> ff_liabs_curr { get; set; }
        public Nullable<double> ff_debt_st { get; set; }
        public Nullable<double> ff_pay_acct { get; set; }
        public Nullable<double> ff_accr_exp_xpayr { get; set; }
        public Nullable<double> ff_ins_liabs_pol { get; set; }
        public Nullable<double> ff_debt_lt { get; set; }
        public Nullable<double> ff_dfd_tax_itc { get; set; }
        public Nullable<double> ff_liabs_xmin_int_accum { get; set; }
        public Nullable<double> ff_pfd_stk { get; set; }
        public Nullable<double> ff_com_eq { get; set; }
        public Nullable<double> ff_debt { get; set; }
        public Nullable<double> ff_shldrs_eq { get; set; }
        public Nullable<double> ff_tier1_cap { get; set; }
        public Nullable<double> ff_tier2_cap { get; set; }
        public Nullable<double> ff_net_inc_cf { get; set; }
        public Nullable<double> ff_dep_exp_cf { get; set; }
        public Nullable<double> ff_non_cash { get; set; }
        public Nullable<double> ff_funds_oper_gross { get; set; }
        public Nullable<double> ff_xord_cf { get; set; }
        public Nullable<double> ff_wkcap_chg { get; set; }
        public Nullable<double> ff_acq_bus_cf { get; set; }
        public Nullable<double> ff_loan_incr_cf { get; set; }
        public Nullable<double> ff_loan_decr_cf { get; set; }
        public Nullable<double> ff_sale_assets_bus_cf { get; set; }
        public Nullable<double> ff_invest_activ_cf { get; set; }
        public Nullable<double> ff_invest_sources_cf { get; set; }
        public Nullable<double> ff_div_cf { get; set; }
        public Nullable<double> ff_deps_decr_cf { get; set; }
        public Nullable<double> ff_deps_incr_cf { get; set; }
        public Nullable<double> ff_for_exch_cf { get; set; }
        public Nullable<double> ff_chg_cash_cf { get; set; }
        public Nullable<double> ff_eps_reported { get; set; }
        public Nullable<double> ff_bps { get; set; }
        public Nullable<double> ff_com_shs_out_eps_basic { get; set; }
        public Nullable<double> ff_com_shs_out_eps_dil { get; set; }
        public Nullable<double> ff_com_shs_out { get; set; }
        public Nullable<double> ff_price_close_fp { get; set; }
        public string ff_actg_standard { get; set; }
        public Nullable<int> ff_fy_length_days { get; set; }
        public Nullable<double> ff_prov_risk { get; set; }
        public Nullable<double> ff_consol_net_inc { get; set; }
        public Nullable<double> ff_eq_tot { get; set; }
        public Nullable<double> ff_eps_basic { get; set; }
        public Nullable<double> ff_com_shs_out_eps { get; set; }
        public Nullable<double> ff_exp_tot { get; set; }
        public Nullable<double> ff_pay_tax { get; set; }
        public Nullable<double> ff_dfd_tax { get; set; }
        public Nullable<double> ff_min_int_accum { get; set; }
        public Nullable<double> ff_liabs_shldrs_eq { get; set; }
        public Nullable<double> ff_loan_net { get; set; }
        public Nullable<double> ff_invest_aff { get; set; }
        public Nullable<double> ff_ppe_net { get; set; }
        public Nullable<double> ff_rsrv_noneq { get; set; }
        public Nullable<double> ff_deps_cust { get; set; }
        public Nullable<double> ff_receiv_st { get; set; }
        public Nullable<double> ff_dps { get; set; }
        public Nullable<double> ff_dps_gross { get; set; }
        public Nullable<double> ff_dfd_tax_db { get; set; }
        public Nullable<double> ff_dfd_tax_cr { get; set; }
        public Nullable<double> ff_receiv_int { get; set; }
        public Nullable<System.DateTime> ff_eps_rpt_date { get; set; }
        public Nullable<System.DateTime> ff_source_is_date { get; set; }
        public Nullable<System.DateTime> ff_source_bs_date { get; set; }
        public Nullable<System.DateTime> ff_source_cf_date { get; set; }
    }
}
