//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_basic_ltm_v2
    {
        public string fs_perm_sec_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> adjdate { get; set; }
        public string currency { get; set; }
        public decimal ff_fpnc { get; set; }
        public Nullable<double> ff_sales { get; set; }
        public Nullable<double> ff_int_inc { get; set; }
        public Nullable<double> ff_non_int_inc { get; set; }
        public Nullable<double> ff_gross_inc { get; set; }
        public Nullable<double> ff_oper_exp_oth { get; set; }
        public Nullable<double> ff_oper_exp_tot { get; set; }
        public Nullable<double> ff_oper_inc { get; set; }
        public Nullable<double> ff_int_exp_tot { get; set; }
        public Nullable<double> ff_loan_loss_prov { get; set; }
        public Nullable<double> ff_non_int_exp { get; set; }
        public Nullable<double> ff_ptx_xord_chrg { get; set; }
        public Nullable<double> ff_ptx_xord_cr { get; set; }
        public Nullable<double> ff_ptx_inc { get; set; }
        public Nullable<double> ff_inc_tax { get; set; }
        public Nullable<double> ff_min_int_exp { get; set; }
        public Nullable<double> ff_eq_aff_inc { get; set; }
        public Nullable<double> ff_net_income { get; set; }
        public Nullable<double> ff_div_pfd { get; set; }
        public Nullable<double> ff_net_inc_cf { get; set; }
        public Nullable<double> ff_dep_exp_cf { get; set; }
        public Nullable<double> ff_non_cash { get; set; }
        public Nullable<double> ff_funds_oper_gross { get; set; }
        public Nullable<double> ff_xord_cf { get; set; }
        public Nullable<double> ff_wkcap_chg { get; set; }
        public Nullable<double> ff_acq_bus_cf { get; set; }
        public Nullable<double> ff_loan_incr_cf { get; set; }
        public Nullable<double> ff_loan_decr_cf { get; set; }
        public Nullable<double> ff_sale_assets_bus_cf { get; set; }
        public Nullable<double> ff_invest_activ_cf { get; set; }
        public Nullable<double> ff_invest_sources_cf { get; set; }
        public Nullable<double> ff_div_cf { get; set; }
        public Nullable<double> ff_deps_decr_cf { get; set; }
        public Nullable<double> ff_deps_incr_cf { get; set; }
        public Nullable<double> ff_for_exch_cf { get; set; }
        public Nullable<double> ff_chg_cash_cf { get; set; }
        public Nullable<double> ff_consol_net_inc { get; set; }
        public Nullable<double> ff_eps_basic { get; set; }
        public Nullable<double> ff_exp_tot { get; set; }
    }
}
