//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_metadata
    {
        public string table_name { get; set; }
        public string field_name { get; set; }
        public short curindicator { get; set; }
        public string splitindicator { get; set; }
        public Nullable<double> unitfactor { get; set; }
        public string description { get; set; }
    }
}
