//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_segreg_af
    {
        public string fs_perm_sec_id { get; set; }
        public System.DateTime date { get; set; }
        public string ff_segment_type { get; set; }
        public int ff_segment_num { get; set; }
        public Nullable<System.DateTime> adjdate { get; set; }
        public string currency { get; set; }
        public string label { get; set; }
        public Nullable<double> sales { get; set; }
        public Nullable<double> opinc { get; set; }
        public Nullable<double> assets { get; set; }
        public Nullable<double> capex { get; set; }
        public Nullable<double> dep { get; set; }
    }
}
