//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ff_stitch_af
    {
        public string fs_perm_sec_id { get; set; }
        public System.DateTime date { get; set; }
        public string stitched_fs_perm_sec_id { get; set; }
    }
}
