//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class fref_security_type_map
    {
        public string fref_security_type_code { get; set; }
        public string fref_security_type_desc { get; set; }
        public string fref_security_type_long_desc { get; set; }
    }
}
