//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class fx_rates_usd
    {
        public string iso_currency { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> exch_rate_usd { get; set; }
        public Nullable<double> exch_rate_per_usd { get; set; }
    }
}
