//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_address
    {
        public int address_id { get; set; }
        public string city_state_zip { get; set; }
        public string location_street1 { get; set; }
        public string location_street2 { get; set; }
        public string location_street3 { get; set; }
        public string iso_country { get; set; }
        public string tele_full { get; set; }
        public string fax_full { get; set; }
    }
}
