//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_entity_sector
    {
        public string factset_entity_id { get; set; }
        public string primary_sic_code { get; set; }
        public string industry_code { get; set; }
        public string sector_code { get; set; }
    }
}
