//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_entity
    {
        public string factset_entity_id { get; set; }
        public string entity_proper_name { get; set; }
        public string iso_country { get; set; }
        public string entity_type { get; set; }
    }
}
