//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_security_sedol
    {
        public string fs_perm_sec_id { get; set; }
        public string sedol { get; set; }
        public string proper_name { get; set; }
        public string factset_entity_id { get; set; }
        public string fs_primary_equity_id { get; set; }
        public string fs_primary_listing_id { get; set; }
        public short inactive_flag { get; set; }
        public string fref_security_type { get; set; }
    }
}
