//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class nace_classification_map
    {
        public string nace_code { get; set; }
        public string nace_desc { get; set; }
        public string nace_group_code { get; set; }
        public string nace_group_desc { get; set; }
        public string nace_division_code { get; set; }
        public string nace_division_desc { get; set; }
        public string nace_section_code { get; set; }
        public string nace_section_desc { get; set; }
    }
}
