//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factset.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class state_province_map
    {
        public string state_province_code { get; set; }
        public string state_province_desc { get; set; }
        public string iso_country { get; set; }
        public string region_name { get; set; }
    }
}
